In [2]:
import numpy as np   ## np is alias or pet name

In [6]:
Distance =[2,4,6,8,10]
Time =[10,20,30,40,5]

In [7]:
Speed= Distance/Time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [8]:
Num_Distance = np.array(Distance)
Num_Time = np.array(Time)

In [9]:
Speed = Num_Distance/Num_Time
Speed

array([0.2, 0.2, 0.2, 0.2, 2. ])

In [10]:
type(Speed)

numpy.ndarray

In [11]:
list1=list(range(1,100,5))
list1

[1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96]

In [12]:
for i in range(len(list1)):
    list1[i]=list1[i]+5
print(list1)    

[6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96, 101]


In [13]:
arr1 = np.arange(1,100,5)
arr1

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [14]:
arr1=arr1+5
arr1

array([  6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,  66,
        71,  76,  81,  86,  91,  96, 101])

# 2.Speed

In [16]:
%%time
for i in range(1000):
    list1=list(range(1,1000,3))
    list2=list(range(2,1001,3))
    list3=[]
    for j in range(len(list2)):
        list3.append(list1[j]+list2[j])
list3        

CPU times: total: 93.8 ms
Wall time: 148 ms


[3,
 9,
 15,
 21,
 27,
 33,
 39,
 45,
 51,
 57,
 63,
 69,
 75,
 81,
 87,
 93,
 99,
 105,
 111,
 117,
 123,
 129,
 135,
 141,
 147,
 153,
 159,
 165,
 171,
 177,
 183,
 189,
 195,
 201,
 207,
 213,
 219,
 225,
 231,
 237,
 243,
 249,
 255,
 261,
 267,
 273,
 279,
 285,
 291,
 297,
 303,
 309,
 315,
 321,
 327,
 333,
 339,
 345,
 351,
 357,
 363,
 369,
 375,
 381,
 387,
 393,
 399,
 405,
 411,
 417,
 423,
 429,
 435,
 441,
 447,
 453,
 459,
 465,
 471,
 477,
 483,
 489,
 495,
 501,
 507,
 513,
 519,
 525,
 531,
 537,
 543,
 549,
 555,
 561,
 567,
 573,
 579,
 585,
 591,
 597,
 603,
 609,
 615,
 621,
 627,
 633,
 639,
 645,
 651,
 657,
 663,
 669,
 675,
 681,
 687,
 693,
 699,
 705,
 711,
 717,
 723,
 729,
 735,
 741,
 747,
 753,
 759,
 765,
 771,
 777,
 783,
 789,
 795,
 801,
 807,
 813,
 819,
 825,
 831,
 837,
 843,
 849,
 855,
 861,
 867,
 873,
 879,
 885,
 891,
 897,
 903,
 909,
 915,
 921,
 927,
 933,
 939,
 945,
 951,
 957,
 963,
 969,
 975,
 981,
 987,
 993,
 999,
 1005,
 1011,
 10

In [20]:
%%time
for i in range(1000):
    a = np.arange(1,1000,3)
    b = np.arange(2,1001,3)
    c=a+b
c       

CPU times: total: 0 ns
Wall time: 10.6 ms


array([   3,    9,   15,   21,   27,   33,   39,   45,   51,   57,   63,
         69,   75,   81,   87,   93,   99,  105,  111,  117,  123,  129,
        135,  141,  147,  153,  159,  165,  171,  177,  183,  189,  195,
        201,  207,  213,  219,  225,  231,  237,  243,  249,  255,  261,
        267,  273,  279,  285,  291,  297,  303,  309,  315,  321,  327,
        333,  339,  345,  351,  357,  363,  369,  375,  381,  387,  393,
        399,  405,  411,  417,  423,  429,  435,  441,  447,  453,  459,
        465,  471,  477,  483,  489,  495,  501,  507,  513,  519,  525,
        531,  537,  543,  549,  555,  561,  567,  573,  579,  585,  591,
        597,  603,  609,  615,  621,  627,  633,  639,  645,  651,  657,
        663,  669,  675,  681,  687,  693,  699,  705,  711,  717,  723,
        729,  735,  741,  747,  753,  759,  765,  771,  777,  783,  789,
        795,  801,  807,  813,  819,  825,  831,  837,  843,  849,  855,
        861,  867,  873,  879,  885,  891,  897,  9

# Memory

In [3]:
import sys
python_list=[10,20,30,40,50,60]
numpy_array=np.array(python_list)
sizeof_pl=sys.getsizeof(1)*len(python_list)
sizeof_pl

168

In [5]:
sizeof_na=numpy_array.itemsize*numpy_array.size
sizeof_na

24

In [6]:
numpy_array.itemsize

4

### Numpy Arrays

#### 1. Create using python list

In [7]:
list1 = [10,20,30]

In [8]:
np.array(list1)

array([10, 20, 30])

In [9]:
matrix=[[10,20,30],[40,50,60],[70,80,90]]

In [10]:
type(matrix)

list

In [11]:
np.array(matrix)  # multidimentional matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [12]:
np.matrix(matrix)    # Not recomended  (only for matrix operations)

matrix([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

#### 2. Using Inbuild methods

##### a) arange

In [13]:
np.arange(19,1,-2)

array([19, 17, 15, 13, 11,  9,  7,  5,  3])

## What would be the output of following code?

In [15]:
np.arange(-1,4,1)

array([-1,  0,  1,  2,  3])

#### b) Using Zeros and ones

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### c) Using Linspace

In [20]:
np.linspace(2,10,5)  #returns an array of evenly spaced values within the specified interval [start, stop , range].

array([ 2.,  4.,  6.,  8., 10.])

In [22]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### d) Using eye

In [23]:
np.eye(3) ## Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(6,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## 3. Generating Random numbers

### a. rand
Uniformly distributed random numbers over [0,1]

In [26]:
np.random.rand(7)

array([0.46482899, 0.24150882, 0.94541368, 0.98493275, 0.55985251,
       0.0897127 , 0.91071719])

In [27]:
np.random.rand(3,4)

array([[0.64506804, 0.33848705, 0.55130925, 0.3625711 ],
       [0.64742208, 0.55980487, 0.844982  , 0.77975953],
       [0.75214043, 0.0017662 , 0.17151832, 0.19256715]])

### b. randn
generates normally distributed random numbers

In [29]:
np.random.randn(5)

array([ 0.59380472,  1.76064622,  0.1313626 , -0.51065451,  0.03111329])

In [30]:
np.random.randn(4,4)

array([[-0.41318283,  0.32452622, -1.39607958, -2.2103406 ],
       [ 0.72398739, -0.75237661,  1.27601643, -0.89910525],
       [-0.92924871, -0.77708689,  0.1931341 ,  0.92323413],
       [-0.66841683, -0.80922249,  0.25836409,  0.16618418]])

### c. randint
generates random integers over given range

In [31]:
np.random.randint(10,100,5)

array([40, 29, 29, 49, 44])

## Which of the following(s) has the ability to generate 4 numbers ranging from 2 to 8
np.linspace(2,8,4) 
np.random.randint(2,8,4)
np.random.randint(2,9,4)
np.linspace(2,9,4)

In [32]:
np.linspace(2,8,4)

array([2., 4., 6., 8.])

In [33]:
np.random.randint(2,8,4)

array([2, 4, 7, 7])

In [34]:
np.random.randint(2,9,4) 

array([4, 6, 6, 7])

In [35]:
np.linspace(2,9,4)

array([2.        , 4.33333333, 6.66666667, 9.        ])