In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,17)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [3]:
arr1[7] ## Positive indexing

8

In [4]:
arr1[-2]  ## Negative indexing

15

In [5]:
arr1[1:5]    # It gives the numbers between index 1 to 5

array([2, 3, 4, 5])

In [6]:
arr1[:3]   # upto the 2nd index

array([1, 2, 3])

In [7]:
arr1[8:]   ## Start from 9th index

array([ 9, 10, 11, 12, 13, 14, 15, 16])

In [8]:
arr1[::1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [10]:
arr2=arr1.reshape(4,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
arr3=np.array(([10,20,30],[40,50,60],[70,80,90],[4,5,6]))
arr3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [ 4,  5,  6]])

In [13]:
arr3[1]

array([40, 50, 60])

In [14]:
arr3[2:]

array([[70, 80, 90],
       [ 4,  5,  6]])

In [15]:
arr3[0,1]

20

In [16]:
arr3[2,1]

80

In [17]:
arr3[0:2,1:3]   #[:2,1:]

array([[20, 30],
       [50, 60]])

In [18]:
arr3[2:4,:2]

array([[70, 80],
       [ 4,  5]])

In [19]:
arr3[:,2:3]

array([[30],
       [60],
       [90],
       [ 6]])

## Quiz
What will the output of following lines of code
arr_2d=np.arange(16).reshape(4,4)arr_2d[2:4][1:2]

In [23]:
arr_2d=np.arange(16).reshape(4,4) 
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
arr_2d[2:4][1:2]

array([[12, 13, 14, 15]])

## Selection

In [25]:
a1=np.arange(1,21)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
a1>7

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [27]:
a1[a1>7]   # actual value

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
np.where(a1>7)   ## It is for the indices

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)

In [29]:
a1[np.where(a1>7)]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
np.where(a1>7,a1,5)

array([ 5,  5,  5,  5,  5,  5,  5,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
np.where(a1<5,a1,10*a1)

array([  1,   2,   3,   4,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])