In [1]:
import numpy as np

In [2]:
arr=np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [3]:
arr2=arr+arr
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [4]:
arr3=arr*arr
arr3

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [5]:
a1=np.array([1,2,3,4])

In [6]:
a1**3

array([ 1,  8, 27, 64], dtype=int32)

In [7]:
div=arr3/arr2
div

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [8]:
sq=np.square(a1)
sq

array([ 1,  4,  9, 16])

In [9]:
sr=np.sqrt(sq)
sr

array([1., 2., 3., 4.])

In [10]:
a2=np.array([10,2,20,3,4,50,6])

In [11]:
sorted_array=np.sort(a2)
sorted_array

array([ 2,  3,  4,  6, 10, 20, 50])

In [12]:
np.min(a2)

2

In [13]:
np.max(a2)

50

In [14]:
np.exp(a2)

array([2.20264658e+04, 7.38905610e+00, 4.85165195e+08, 2.00855369e+01,
       5.45981500e+01, 5.18470553e+21, 4.03428793e+02])

In [15]:
np.log(a2)

array([2.30258509, 0.69314718, 2.99573227, 1.09861229, 1.38629436,
       3.91202301, 1.79175947])

In [16]:
np.sum(a2)

95

In [17]:
np.tan(a2)

array([ 0.64836083, -2.18503986,  2.23716094, -0.14254654,  1.15782128,
       -0.27190061, -0.29100619])

In [18]:
a2

array([10,  2, 20,  3,  4, 50,  6])

In [19]:
sorted_array

array([ 2,  3,  4,  6, 10, 20, 50])

In [20]:
np.maximum(a2,sorted_array)

array([10,  3, 20,  6, 10, 50, 50])